/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as PlaygroundSlugRouteImport } from './routes/playground/$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectRouteImport } from './routes/projects/$project'
import { Route as WritingIndexRouteImport } from './routes/writing/index'
import { Route as WritingSlugRouteImport } from './routes/writing/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundSlugRoute = PlaygroundSlugRouteImport.update({
  id: '/playground/$slug',
  path: '/playground/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectRoute = ProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingIndexRoute = WritingIndexRouteImport.update({
  id: '/writing/',
  path: '/writing/',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingSlugRoute = WritingSlugRouteImport.update({
  id: '/writing/$slug',
  path: '/writing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground/$slug': typeof PlaygroundSlugRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground/$slug': typeof PlaygroundSlugRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/playground': typeof PlaygroundIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/writing': typeof WritingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/playground/$slug': typeof PlaygroundSlugRoute
  '/projects/$project': typeof ProjectsProjectRoute
  '/writing/$slug': typeof WritingSlugRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/writing/': typeof WritingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/playground/$slug'
    | '/projects/$project'
    | '/writing/$slug'
    | '/playground/'
    | '/projects/'
    | '/writing/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/playground/$slug'
    | '/projects/$project'
    | '/writing/$slug'
    | '/playground'
    | '/projects'
    | '/writing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/playground/$slug'
    | '/projects/$project'
    | '/writing/$slug'
    | '/playground/'
    | '/projects/'
    | '/writing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  PlaygroundSlugRoute: typeof PlaygroundSlugRoute
  ProjectsProjectRoute: typeof ProjectsProjectRoute
  WritingSlugRoute: typeof WritingSlugRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
  WritingIndexRoute: typeof WritingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/$slug': {
      id: '/playground/$slug'
      path: '/playground/$slug'
      fullPath: '/playground/$slug'
      preLoaderRoute: typeof PlaygroundSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$project': {
      id: '/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof ProjectsProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/': {
      id: '/writing/'
      path: '/writing'
      fullPath: '/writing/'
      preLoaderRoute: typeof WritingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writing/$slug': {
      id: '/writing/$slug'
      path: '/writing/$slug'
      fullPath: '/writing/$slug'
      preLoaderRoute: typeof WritingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  PlaygroundSlugRoute: PlaygroundSlugRoute,
  ProjectsProjectRoute: ProjectsProjectRoute,
  WritingSlugRoute: WritingSlugRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
  WritingIndexRoute: WritingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
